"use strict";
const QUESTION_BANK = window.QUESTION_BANK || [];
const EXAM_SECONDS = 95 * 60;
const STORAGE_KEY = "clep-college-math-exam-v4";
const app = document.getElementById("app");
let timerHandle = null;
function hashString(v){let h=2166136261>>>0;for(let i=0;i<v.length;i++){h^=v.charCodeAt(i);h=Math.imul(h,16777619)}return h>>>0}
function rng(seed){return function(){let t=seed+=0x6D2B79F5;t=Math.imul(t^(t>>>15),t|1);t^=t+Math.imul(t^(t>>>7),t|61);return((t^(t>>>14))>>>0)/4294967296}}
function shuffle(a,seed){const out=a.slice(),r=rng(seed>>>0);for(let i=out.length-1;i>0;i--){const j=Math.floor(r()*(i+1));[out[i],out[j]]=[out[j],out[i]]}return out}
function orderedQuestions(seed){return shuffle(QUESTION_BANK,seed)}
function orderedChoices(q,seed){return shuffle(q.choices.map((text,originalIndex)=>({text,originalIndex})),(seed^hashString(q.id))>>>0)}
function save(a){localStorage.setItem(STORAGE_KEY,JSON.stringify(a))}
function load(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY)||"null")}catch{return null}}
function clear(){localStorage.removeItem(STORAGE_KEY)}
function esc(v){return String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function remaining(a){return Math.max(0,Math.ceil((a.startedAt+EXAM_SECONDS*1000-Date.now())/1000))}
function fmt(s){s=Math.max(0,Math.round(s));return `${Math.floor(s/60)}:${String(s%60).padStart(2,"0")}`}
function answered(q,a){if(a===undefined||a===null)return false;if(q.type==="choice")return typeof a==="number";if(q.type==="numeric")return String(a).trim()!=="";if(q.type==="matrix")return q.rows.every((_,i)=>Object.prototype.hasOwnProperty.call(a,String(i)));return false}
function correct(q,a){if(!answered(q,a))return false;if(q.type==="choice")return a===q.answer;if(q.type==="numeric"){const n=Number(String(a).replace(/,/g,"").trim());return Number.isFinite(n)&&Math.abs(n-q.answer)<=(q.tolerance||1e-9)}return q.rows.every((_,i)=>a[String(i)]===q.answers[i])}
function answerText(q,a){if(!answered(q,a))return "Unanswered";if(q.type==="choice")return q.choices[a];if(q.type==="numeric")return `${a}${q.suffix?` ${q.suffix}`:""}`;return q.rows.map((r,i)=>`${r}: ${q.columns[a[String(i)]]||"Unanswered"}`).join("; ")}
function correctText(q){if(q.type==="choice")return q.choices[q.answer];if(q.type==="numeric")return `${q.answer}${q.suffix?` ${q.suffix}`:""}`;return q.rows.map((r,i)=>`${r}: ${q.columns[q.answers[i]]}`).join("; ")}
function renderIntro(){
 if(QUESTION_BANK.length!==60){app.innerHTML=`<section class="hero"><h1>Exam setup error</h1><p>Expected 60 questions but loaded ${QUESTION_BANK.length}. Please refresh.</p></section>`;return}
 const saved=load(), active=saved&&!saved.submittedAt&&remaining(saved)>0;
 app.innerHTML=`<section class="hero"><div class="eyebrow">CLEP College Mathematics Practice</div><h1>Interactive Practice Exam</h1><p class="lead">60 original questions aligned to the CLEP College Mathematics content areas and designed for a 95-minute timed practice session.</p><div class="meta-grid"><div class="meta-item"><strong>60 questions</strong><span>Mixed content areas</span></div><div class="meta-item"><strong>95 minutes</strong><span>Timed practice</span></div><div class="meta-item"><strong>Automatic grading</strong><span>Review missed questions</span></div></div><h2>Directions</h2><ul class="instructions"><li>Select the best answer unless numerical entry or table classification is requested.</li><li>Use a scientific nongraphing calculator when appropriate.</li><li>You may flag questions and return before submitting.</li></ul><div class="form-row"><label for="student-name">Student name <span class="note">(optional)</span></label><input id="student-name" class="text-input" maxlength="80" placeholder="Enter name"></div><div class="actions"><button id="start-btn" class="btn btn-primary">Start New Attempt</button>${active?`<button id="resume-btn" class="btn">Resume Saved Attempt (${fmt(remaining(saved))} left)</button>`:""}</div><p class="footer-note">Independent practice material. Not affiliated with or endorsed by College Board.</p></section>`;
 document.getElementById("start-btn").onclick=()=>{const a={seed:(Date.now()^Math.floor(Math.random()*0x7fffffff))>>>0,studentName:document.getElementById("student-name").value.trim(),startedAt:Date.now(),currentIndex:0,answers:{},flags:[]};save(a);runExam(a)};
 if(active)document.getElementById("resume-btn").onclick=()=>runExam(saved);
}
function runExam(a){
 if(timerHandle)clearInterval(timerHandle);
 const order=orderedQuestions(a.seed);a.currentIndex=Math.min(Math.max(a.currentIndex||0,0),59);save(a);
 app.innerHTML=`<section class="exam-topbar"><div class="top-stat"><span class="label">Question</span><strong id="top-q"></strong></div><div class="top-stat"><span class="label">Answered</span><strong id="top-answered"></strong></div><div class="progress-wrap"><div class="progress-track"><div id="progress-bar" class="progress-bar"></div></div></div><div id="timer-box" class="top-stat timer"><span class="label">Time left</span><strong id="timer"></strong></div></section><section id="question-card" class="question-card"></section><section class="navigator-panel"><div class="navigator-head"><strong>Question navigator</strong><div class="legend"><span class="lg-answered">Answered</span><span class="lg-flagged">Flagged</span></div></div><div id="navigator" class="navigator"></div><div class="submit-row"><button id="submit-btn" class="btn btn-primary">Submit Exam & Grade</button></div></section>`;
 function renderQuestion(){const q=order[a.currentIndex],ans=a.answers[q.id],flag=a.flags.includes(q.id);let response="";
  if(q.type==="choice")response=`<fieldset class="choice-list"><legend class="sr-only">Answer choices</legend>${orderedChoices(q,a.seed).map((c,p)=>`<label class="choice ${ans===c.originalIndex?"selected":""}"><input type="radio" name="choice" value="${c.originalIndex}" ${ans===c.originalIndex?"checked":""}><span class="choice-letter">${String.fromCharCode(65+p)}.</span><span>${esc(c.text)}</span></label>`).join("")}</fieldset>`;
  else if(q.type==="numeric")response=`<div class="numeric-wrap"><label for="numeric-answer">Enter your answer</label><input id="numeric-answer" class="numeric-input" value="${ans==null?"":esc(ans)}" inputmode="decimal">${q.suffix?`<span>${esc(q.suffix)}</span>`:""}</div>`;
  else response=`<table class="matrix-table"><thead><tr><th>Expression</th>${q.columns.map(c=>`<th>${esc(c)}</th>`).join("")}</tr></thead><tbody>${q.rows.map((r,i)=>`<tr><td>${esc(r)}</td>${q.columns.map((c,j)=>`<td><label><input type="radio" name="row-${i}" value="${j}" ${ans&&ans[String(i)]===j?"checked":""}><span class="sr-only">${esc(c)}</span></label></td>`).join("")}</tr>`).join("")}</tbody></table>`;
  document.getElementById("question-card").innerHTML=`<div class="question-number">Question ${a.currentIndex+1} of 60</div>${q.stimulusHtml||""}<div class="question-stem">${esc(q.stem)}</div>${response}<div class="question-actions"><button id="prev-btn" class="btn" ${a.currentIndex===0?"disabled":""}>Previous</button><button id="flag-btn" class="btn ${flag?"flag-active":""}">${flag?"Unflag":"Flag for review"}</button><button id="next-btn" class="btn btn-primary">${a.currentIndex===59?"Review":"Next"}</button></div>`;
  document.querySelectorAll('input[name="choice"]').forEach(el=>el.onchange=()=>{a.answers[q.id]=Number(el.value);save(a);renderQuestion();renderNav();updateTop()});
  const num=document.getElementById("numeric-answer");if(num)num.oninput=()=>{a.answers[q.id]=num.value;save(a);renderNav();updateTop()};
  if(q.type==="matrix")q.rows.forEach((_,i)=>document.querySelectorAll(`input[name="row-${i}"]`).forEach(el=>el.onchange=()=>{a.answers[q.id]=a.answers[q.id]||{};a.answers[q.id][String(i)]=Number(el.value);save(a);renderNav();updateTop()}));
  document.getElementById("prev-btn").onclick=()=>{if(a.currentIndex>0){a.currentIndex--;save(a);renderQuestion();renderNav();updateTop();window.scrollTo(0,0)}};
  document.getElementById("next-btn").onclick=()=>{if(a.currentIndex<59){a.currentIndex++;save(a);renderQuestion();renderNav();updateTop();window.scrollTo(0,0)}else document.getElementById("navigator").scrollIntoView({behavior:"smooth"})};
  document.getElementById("flag-btn").onclick=()=>{a.flags=a.flags.includes(q.id)?a.flags.filter(x=>x!==q.id):[...a.flags,q.id];save(a);renderQuestion();renderNav()};
 }
 function renderNav(){const n=document.getElementById("navigator");n.innerHTML=order.map((q,i)=>`<button class="nav-q ${answered(q,a.answers[q.id])?"answered":""} ${a.flags.includes(q.id)?"flagged":""} ${i===a.currentIndex?"current":""}" data-i="${i}">${i+1}</button>`).join("");n.querySelectorAll("button").forEach(b=>b.onclick=()=>{a.currentIndex=Number(b.dataset.i);save(a);renderQuestion();renderNav();updateTop();window.scrollTo(0,0)})}
 function updateTop(){const c=order.filter(q=>answered(q,a.answers[q.id])).length;document.getElementById("top-q").textContent=`${a.currentIndex+1} / 60`;document.getElementById("top-answered").textContent=`${c} / 60`;document.getElementById("progress-bar").style.width=`${((a.currentIndex+1)/60)*100}%`}
 function tick(){const left=remaining(a);document.getElementById("timer").textContent=fmt(left);document.getElementById("timer-box").classList.toggle("low",left<=600);if(left<=0){clearInterval(timerHandle);grade(a,true)}}
 document.getElementById("submit-btn").onclick=()=>{const u=order.filter(q=>!answered(q,a.answers[q.id])).length;if(confirm(u?`You have ${u} unanswered question${u===1?"":"s"}. Submit anyway?`:"Submit the exam for grading?"))grade(a,false)};
 renderQuestion();renderNav();updateTop();tick();timerHandle=setInterval(tick,1000);
}
function grade(a,timedOut){if(timerHandle)clearInterval(timerHandle);a.submittedAt=Date.now();save(a);const order=orderedQuestions(a.seed),res=order.map((q,i)=>({q,i,ans:a.answers[q.id],ok:correct(q,a.answers[q.id])})),score=res.filter(x=>x.ok).length,pct=score/60*100,unanswered=res.filter(x=>!answered(x.q,x.ans)).length;const topics=["Algebra & Functions","Financial Mathematics","Data Analysis & Statistics","Logic & Sets","Counting & Probability","Geometry","Numbers"];
 app.innerHTML=`<div class="results-wrap"><section class="results-card"><div class="eyebrow">${timedOut?"Time limit reached":"Exam submitted"}</div><h1>${a.studentName?esc(a.studentName)+" - ":""}Results</h1><div class="score-line"><div class="score-big">${score} / 60</div><div class="score-sub"><strong>${pct.toFixed(1)}%</strong> raw practice score${unanswered?`<br>${unanswered} unanswered`:""}</div></div><p class="note">This is a raw practice score, not a CLEP scaled score.</p></section><section class="results-card"><h2>Performance by content area</h2><table class="breakdown"><tbody>${topics.map(t=>{const s=res.filter(x=>x.q.topic===t);return `<tr><td>${esc(t)}</td><td><strong>${s.filter(x=>x.ok).length}/${s.length}</strong></td></tr>`}).join("")}</tbody></table></section><section class="results-card no-print"><div class="actions"><button id="print-results" class="btn">Print / Save as PDF</button><button id="new-attempt" class="btn btn-primary">Start New Attempt</button></div></section><section class="results-card"><h2>Questions to review</h2>${score===60?"<p>All 60 questions were answered correctly.</p>":res.filter(x=>!x.ok).map(x=>`<article class="review-item bad"><div class="review-meta">Question ${x.i+1} · ${esc(x.q.topic)}</div><div class="review-stem">${esc(x.q.stem)}</div><div class="answer-line">Your answer: <span class="wrong-text">${esc(answerText(x.q,x.ans))}</span></div><div class="answer-line">Correct answer: <span class="correct-text">${esc(correctText(x.q))}</span></div><div class="explanation"><strong>Why:</strong> ${esc(x.q.explanation)}</div></article>`).join("")}</section></div>`;
 document.getElementById("print-results").onclick=()=>window.print();document.getElementById("new-attempt").onclick=()=>{clear();renderIntro();window.scrollTo(0,0)};
}
renderIntro();
