window.CLEP=window.CLEP||{};
CLEP.questions=window.CLEP_QUESTIONS||[];
CLEP.TOTAL=CLEP.questions.length;
CLEP.EXAM_SECONDS=95*60;
CLEP.ACTIVE_KEY='clep-cb-variant-active-v1';
CLEP.RESULTS_KEY='clep-cb-variant-results-v1';
CLEP.app=document.getElementById('app');
CLEP.timer=undefined;
CLEP.esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
CLEP.keyFor=q=>String(q.id);
CLEP.nowId=()=>`${Date.now()}-${Math.random().toString(36).slice(2,8)}`;
CLEP.loadActive=()=>{try{return JSON.parse(localStorage.getItem(CLEP.ACTIVE_KEY)||'null')}catch{return null}};
CLEP.saveActive=a=>localStorage.setItem(CLEP.ACTIVE_KEY,JSON.stringify(a));
CLEP.clearActive=()=>localStorage.removeItem(CLEP.ACTIVE_KEY);
CLEP.loadResults=()=>{try{return JSON.parse(localStorage.getItem(CLEP.RESULTS_KEY)||'[]')}catch{return []}};
CLEP.saveResults=items=>localStorage.setItem(CLEP.RESULTS_KEY,JSON.stringify(items.slice(0,50)));
CLEP.remaining=a=>Math.max(0,Math.ceil((a.startedAt+CLEP.EXAM_SECONDS*1000-Date.now())/1000));
CLEP.fmtTime=s=>`${Math.floor(s/60)}:${String(s%60).padStart(2,'0')}`;
CLEP.fmtDate=ms=>new Intl.DateTimeFormat(undefined,{dateStyle:'medium',timeStyle:'short'}).format(new Date(ms));
CLEP.isCorrect=(q,v)=>{if(v===undefined)return false;if(q.type==='mc')return Number(v)===q.answer;if(q.type==='numeric'){const n=Number(v);return Number.isFinite(n)&&Math.abs(n-q.answer)<=(q.tolerance??1e-9)}if(q.type==='matrix'){return Array.isArray(v)&&v.length===q.answer.length&&q.answer.every((a,i)=>Number(v[i])===a)}return false};
CLEP.score=answers=>CLEP.questions.filter(q=>CLEP.isCorrect(q,answers[CLEP.keyFor(q)])).length;
CLEP.answerText=(q,v)=>{if(v===undefined)return'Unanswered';if(q.type==='mc')return q.choices[Number(v)]?.text||'Unanswered';if(q.type==='numeric')return`${v}${q.suffix||''}`;if(q.type==='matrix'&&Array.isArray(v))return q.rows.map((r,i)=>`${r}: ${q.columns[Number(v[i])]??'—'}`).join('; ');return String(v)};
CLEP.correctText=q=>q.type==='mc'?q.choices[q.answer].text:q.type==='numeric'?`${q.answer}${q.suffix||''}`:q.rows.map((r,i)=>`${r}: ${q.columns[q.answer[i]]}`).join('; ');
CLEP.stimulus=q=>!q.stimulus?'':q.stimulus.kind==='svg'?`<div class="stimulus">${renderDiagram(q.stimulus.key)}</div>`:`<div class="stimulus">${q.stimulus.html}</div>`;
CLEP.renderMatrix=(q,arr)=>`<div class="matrix"><table><thead><tr><th>Number</th>${q.columns.map(x=>`<th>${CLEP.esc(x)}</th>`).join('')}</tr></thead><tbody>${q.rows.map((row,ri)=>`<tr><td>${CLEP.esc(row)}</td>${q.columns.map((_,ci)=>`<td><input type="radio" name="matrix-${ri}" data-row="${ri}" value="${ci}" ${arr[ri]===ci?'checked':''} aria-label="${CLEP.esc(row)} ${CLEP.esc(q.columns[ci])}"/></td>`).join('')}</tr>`).join('')}</tbody></table></div>`;
